ValueSet: TNMNVS
Id: TNMNVS
Title: "TNMN VS"
Description: "TNM N-Category"
* insert CCECoreArtifactMetadata(ValueSet,TNMNVS)
* TNMNCS#0 "0"
* TNMNCS#0(i-) "0(i-)"
* TNMNCS#0(i+) "0(i+)"
* TNMNCS#0(mol-) "0(mol-)"
* TNMNCS#0(mol+) "0(mol+)"
* TNMNCS#1 "1"
* TNMNCS#1a "1a"
* TNMNCS#1b "1b"
* TNMNCS#1c "1c"
* TNMNCS#1mi "1mi"
* TNMNCS#2 "2"
* TNMNCS#2a "2a"
* TNMNCS#2b "2b"
* TNMNCS#2c "2c"
* TNMNCS#3 "3"
* TNMNCS#3a "3a"
* TNMNCS#3b "3b"
* TNMNCS#3c "3c"
* TNMNCS#X "X"